// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Session struct {
	ID        int64
	Prompt    string
	Workdir   string
	Status    string
	FinalText string
	Error     string
	CreatedAt string
}

type SessionEvent struct {
	ID        int64
	SessionID int64
	Seq       int64
	Role      string
	Message   string
	CreatedAt string
}
