// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const appendSessionEvent = `-- name: AppendSessionEvent :one
INSERT INTO session_events (session_id, seq, role, message)
VALUES (?, ?, ?, ?)
RETURNING id, session_id, seq, role, message, created_at
`

type AppendSessionEventParams struct {
	SessionID int64
	Seq       int64
	Role      string
	Message   string
}

func (q *Queries) AppendSessionEvent(ctx context.Context, arg AppendSessionEventParams) (SessionEvent, error) {
	row := q.db.QueryRowContext(ctx, appendSessionEvent,
		arg.SessionID,
		arg.Seq,
		arg.Role,
		arg.Message,
	)
	var i SessionEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.Role,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (prompt, workdir)
VALUES (?, ?)
RETURNING id, prompt, workdir, status, final_text, error, created_at
`

type CreateSessionParams struct {
	Prompt  string
	Workdir string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Prompt, arg.Workdir)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.Workdir,
		&i.Status,
		&i.FinalText,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const finishSession = `-- name: FinishSession :one
UPDATE sessions
SET status = ?, final_text = ?, error = ?
WHERE id = ?
RETURNING id, prompt, workdir, status, final_text, error, created_at
`

type FinishSessionParams struct {
	Status    string
	FinalText string
	Error     string
	ID        int64
}

func (q *Queries) FinishSession(ctx context.Context, arg FinishSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, finishSession,
		arg.Status,
		arg.FinalText,
		arg.Error,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.Workdir,
		&i.Status,
		&i.FinalText,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, prompt, workdir, status, final_text, error, created_at FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.Workdir,
		&i.Status,
		&i.FinalText,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionEvents = `-- name: ListSessionEvents :many
SELECT id, session_id, seq, role, message, created_at FROM session_events
WHERE session_id = ?
ORDER BY seq ASC
`

func (q *Queries) ListSessionEvents(ctx context.Context, sessionID int64) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEvents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionEvent
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Role,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, prompt, workdir, status, final_text, error, created_at FROM sessions
ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Prompt,
			&i.Workdir,
			&i.Status,
			&i.FinalText,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
